
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author PC
 */
public class MinesWindow extends javax.swing.JFrame {

    private MinesGame game;
    private DatabaseConnection myDb;
    int l = 0;
    int w;
    int h;
    int mines;

    /**
     * Creates new form MinesWindow
     */
    public MinesWindow() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        backgroundpanel = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        enterBtn = new javax.swing.JButton();
        widthField = new javax.swing.JTextField();
        heightField = new javax.swing.JTextField();
        minesField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        intermediate = new javax.swing.JLabel();
        pro = new javax.swing.JLabel();
        noob = new javax.swing.JLabel();
        loadbutt = new javax.swing.JButton();
        play = new javax.swing.JPanel();
        minesWidget1 = new MinesWidget();
        saveButt = new javax.swing.JButton();
        loadgame = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBar = new javax.swing.JMenu();
        restartBar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundpanel.setLayout(new java.awt.CardLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));

        enterBtn.setText("Enter");
        enterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtnActionPerformed(evt);
            }
        });

        minesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minesFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Width");

        jLabel2.setText("Height");

        jLabel3.setText("Number of mines");

        intermediate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numbers/intermediate.png"))); // NOI18N
        intermediate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intermediateMouseClicked(evt);
            }
        });

        pro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numbers/pro.png"))); // NOI18N
        pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proMouseClicked(evt);
            }
        });

        noob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numbers/noob.png"))); // NOI18N
        noob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noobMouseClicked(evt);
            }
        });

        loadbutt.setText("Load Game");
        loadbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadbuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addComponent(noob)
                                .addGap(47, 47, 47)
                                .addComponent(intermediate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(pro)))))
                .addGap(54, 54, 54))
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterBtn)
                .addGap(48, 48, 48)
                .addComponent(widthField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(minesField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244)
                .addComponent(loadbutt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterBtn)
                    .addComponent(widthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadbutt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addComponent(noob)
                        .addContainerGap())
                    .addComponent(intermediate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pro, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        backgroundpanel.add(menu, "card2");

        play.setBackground(new java.awt.Color(255, 255, 255));
        play.setLayout(new java.awt.BorderLayout());

        minesWidget1.setBackground(new java.awt.Color(255, 255, 255));
        minesWidget1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minesWidget1MouseClicked(evt);
            }
        });

        saveButt.setText("Save");
        saveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtActionPerformed(evt);
            }
        });
        minesWidget1.add(saveButt);
        saveButt.setBounds(880, 20, 72, 23);

        play.add(minesWidget1, java.awt.BorderLayout.CENTER);

        backgroundpanel.add(play, "card3");

        javax.swing.GroupLayout loadgameLayout = new javax.swing.GroupLayout(loadgame);
        loadgame.setLayout(loadgameLayout);
        loadgameLayout.setHorizontalGroup(
            loadgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1185, Short.MAX_VALUE)
        );
        loadgameLayout.setVerticalGroup(
            loadgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        backgroundpanel.add(loadgame, "card4");

        menuBar.setText("Menu");
        menuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBar);

        restartBar.setText("Restart");
        restartBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restartBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(restartBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minesWidget1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minesWidget1MouseClicked
        int w = minesWidget1.getWidth() / minesWidget1.getGame().getPlan().getWidth();
        int h = minesWidget1.getHeight() / minesWidget1.getGame().getPlan().getHeight();
        int s = w < h ? w : h;

        int rows = evt.getX() / s;
        int col = evt.getY() / s;

        minesWidget1.selectPosition(rows, col);

        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (minesWidget1.getGame().getState() == 1) {
                if (minesWidget1.getGame().getPlan().isMineAt(rows, col) && !minesWidget1.getGame().getPlan().isMarkedAt(rows, col)) {

                    minesWidget1.uncoverPosition(rows, col);
                    minesWidget1.getGame().getPlan().uncoverAll();
                    minesWidget1.repaint();
                    JOptionPane.showMessageDialog(null, "You have lost!", "Mines", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    minesWidget1.uncoverPosition(rows, col);
                    if (minesWidget1.getGame().getState() == 3) {
                        minesWidget1.uncoverPosition(rows, col);
                        minesWidget1.getGame().getPlan().uncoverAll();
                        minesWidget1.repaint();
                        JOptionPane.showMessageDialog(null, "You have won!", "Mines", JOptionPane.INFORMATION_MESSAGE);

                    }
                }
            } else {
                return;
            }
        }

        if (evt.getButton() == MouseEvent.BUTTON3) {
            try {
                minesWidget1.markingPosition(rows, col);
            } catch (WrongActionException ex) {
                System.err.println("wrong rows and col or the field is already uncovered!");
            }
        }

        System.out.println("Start" + Integer.toString(l++));
        System.out.println(minesWidget1.getGame().getState());

        minesWidget1.repaint();
//       minesWidget1.update(minesWidget1.getGraphics());
        System.out.println("End" + Integer.toString(l++));
    }//GEN-LAST:event_minesWidget1MouseClicked

    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed

        w = Integer.parseInt(widthField.getText());
        h = Integer.parseInt(heightField.getText());
        mines = Integer.parseInt(minesField.getText());

        game = new MinesGame(w, h, mines);
        minesWidget1.setGame(game);
        widthField.setText("");
        heightField.setText("");
        minesField.setText("");
        menu.setVisible(false);
        play.setVisible(true);
    }//GEN-LAST:event_enterBtnActionPerformed

    private void noobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noobMouseClicked
        game = new MinesGame(9, 9, 10);
        w = 9;
        h = 9;
        mines = 10;
        game = new MinesGame(w, h, mines);
        minesWidget1.setGame(game);
        minesWidget1.repaint();
        menu.setVisible(false);
        play.setVisible(true);


    }//GEN-LAST:event_noobMouseClicked

    private void intermediateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intermediateMouseClicked

        w = 16;
        h = 16;
        mines = 40;
        game = new MinesGame(w, h, mines);
        minesWidget1.setGame(game);
        minesWidget1.repaint();
        menu.setVisible(false);
        play.setVisible(true);
    }//GEN-LAST:event_intermediateMouseClicked

    private void proMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proMouseClicked

        w = 30;
        h = 16;
        mines = 99;
        game = new MinesGame(w, h, mines);
        minesWidget1.setGame(game);
        minesWidget1.repaint();
        menu.setVisible(false);
        play.setVisible(true);
    }//GEN-LAST:event_proMouseClicked

    private void menuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMouseClicked
        play.setVisible(false);
        loadgame.setVisible(false);
        menu.setVisible(true);

    }//GEN-LAST:event_menuBarMouseClicked

    private void restartBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartBarMouseClicked
        game = new MinesGame(w, h, mines);
        minesWidget1.setGame(game);
        minesWidget1.repaint();


    }//GEN-LAST:event_restartBarMouseClicked

    private void loadbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbuttActionPerformed
        // TODO add your handling code here:
        play.setVisible(false);
        menu.setVisible(false);
        loadgame.setVisible(true);

        myDb.connect();


    }//GEN-LAST:event_loadbuttActionPerformed

    private void minesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minesFieldActionPerformed

    private void saveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtActionPerformed
        String userEnteredName = JOptionPane.showInputDialog(this, "Enter a name for the save:");

    if (userEnteredName != null && !userEnteredName.isEmpty()) {
        try (FileOutputStream fos = new FileOutputStream("temp_save.dat")) {
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(minesWidget1.getPlan());
            System.out.println(oos);
            oos.close();

            File binaryFile = new File("temp_save.dat");
            DatabaseConnection.insertSavedGame(userEnteredName, binaryFile);
            binaryFile.delete(); // Delete the temporary file after saving to the database
         } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Cannot save the game to a temporary file! Error: " + ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An error occurred while saving the game to the database! Error: " + ex.getMessage());
        }
    }


    }//GEN-LAST:event_saveButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MinesWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JButton enterBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField heightField;
    private javax.swing.JLabel intermediate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton loadbutt;
    private javax.swing.JPanel loadgame;
    private javax.swing.JPanel menu;
    private javax.swing.JMenu menuBar;
    private javax.swing.JTextField minesField;
    private MinesWidget minesWidget1;
    private javax.swing.JLabel noob;
    private javax.swing.JPanel play;
    private javax.swing.JLabel pro;
    private javax.swing.JMenu restartBar;
    private javax.swing.JButton saveButt;
    private javax.swing.JTextField widthField;
    // End of variables declaration//GEN-END:variables
}
